name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ./react-js/reactapptest

      - name: Build the React app
        run: npm run build
        working-directory: ./react-js/reactapptest

      - name: Deploy to GitHub Pages
        run: npm run deploy
        working-directory: ./react-js/reactapptest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
